### PR TITLE
disable or enable legend

### PR DESCRIPTION
**Pull request by cassiorachid**
I'm suggesting this modification to omit legend because I'm working with a large number of species and the built-in legend of the function doesn't show all of them. I'm manually creating a separate legend to identify the species but I didn't find a way to omit the default legend of the plot. I think this modification would benefit others with the same problem.

### CODE REVIEW

**Comment by mlysy** [comment]
Thanks for the suggestion.  Let me simmer on this for a bit, while I think about the unintended consequences for existing code of adding an argument to this function.

**Comment by cassiorachid** [comment]
No problem. Take your time. Until then, I'm working with my fork with this option.

Also, I've created a routine on my script that makes the legend in a separate plot. Let me know if you want to see how it works.

**Comment by benjaminhlina** [comment]
Hi @cassiorachid and @mlysy, I know this is a bit over a year late, but I have made a vignette of how to plot and represent the outputs from the package in ggplot providing, you @cassiorachid, greater flexibility in legends ect. The blog post is here https://blog.benjaminhlina.com/posts/post-with-code/nicheROVER-ggplot/nicheROVER_ggplot.html. I hope it helps. 

Overall @mlysy the package is great, thank you for building such a great tool!

**Comment by cassiorachid** [comment]
Hi @benjaminhlina.

I appreciate your reply. It is never too late to learn new workflows.  I've saved your post to use later, but it will be great for me.

Thank you!

**Comment by mlysy** [comment]
@cassiorachid after considerable deliberation I decided to follow your suggestion to add a `legend` argument to `niche.plot()` to enable/disable the legend.  I think by making the argument last it's very unlikely to interfere with existing code.  The update is now available here and will be on CRAN in a few days.  

@benjaminhlina thanks for the blog post!  I've now linked to it in the README.

**Comment by benjaminhlina** [comment]
Thanks @mlysy for including the blog post in the README!

**Comment by cassiorachid** [comment]
Hello @mlysy, I'm happy to know that you considered my suggestion. It will be very useful to me. I'll try it later and delete my fork.

Thank you very much!

**Pull request closed without merging**
